export const DASHBOARD_REFRESH_INTERVAL_MS = 15_000;
export const OPERATIONS_REFRESH_INTERVAL_MS = 15_000;
export const ORG_CVE_STATUS_REFRESH_INTERVAL_MS = 10_000;
export const RUN_QUEUE_REFRESH_INTERVAL_MS = 3_000;
