package com.prototype.vulnwatch.dto;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record OrgSpecificCveExposureRecordResponse(
        UUID recordId,
        UUID vulnerabilityId,
        String externalId,
        String title,
        String descriptionSnippet,
        String applicability,
        boolean impacted,
        String impactState,
        String impactReason,
        String reviewReason,
        String severity,
        Double cvssScore,
        Double epssScore,
        boolean inKev,
        long matchedComponentCount,
        long matchedSoftwareCount,
        long matchedAssetCount,
        long applicableComponentCount,
        long impactedComponentCount,
        long notAffectedComponentCount,
        long fixedComponentCount,
        long noPatchComponentCount,
        long underInvestigationComponentCount,
        long unknownComponentCount,
        long openFindings,
        Instant lastEvaluatedAt,
        long eolComponentCount,
        long eosComponentCount,
        boolean hasInvestigationSummary,
        Instant investigationSummaryGeneratedAt,
        String investigationSummaryMode,
        boolean hasAiSolution,
        Instant aiSolutionGeneratedAt,
        String orgImpact,
        UUID suppressedByRuleId,
        String suppressedByRuleName,
        List<String> sources,
        String euvdId,
        String jvndbId,
        boolean includedInCorrelation,
        List<String> includedCorrelationSources,
        List<String> excludedCorrelationSources
) {
}
