package com.prototype.vulnwatch.dto;

public record RiskPolicyRequest(
        Double criticalThreshold,
        Double highThreshold,
        Integer criticalSlaDays,
        Integer highSlaDays,
        Integer mediumSlaDays,
        Integer lowSlaDays,
        Double assetCriticalSlaMultiplier,
        Double assetHighSlaMultiplier,
        Double assetMediumSlaMultiplier,
        Double assetLowSlaMultiplier,
        Boolean autoCloseEnabled,
        String autoCloseAssetIdentifier,
        Integer autoCloseAfterDays,
        String findingGenerationMode,
        String findingsScoreConfig,
        Double agentAutoThreshold,
        Double agentReviewThreshold,
        Integer agentMaxConcurrent,
        Integer autoCloseRequiredConsecutiveMisses,
        Boolean autoCloseNotObservedEnabled,
        Boolean autoCloseComponentRemovedEnabled,
        Boolean autoCloseAssetRetiredEnabled,
        Boolean autoCloseSourceDisabledEnabled,
        Boolean autoCloseDuplicateEnabled,
        Integer autoCloseRunIntervalDays
) {
    public RiskPolicyRequest(
            Double criticalThreshold,
            Double highThreshold,
            Integer criticalSlaDays,
            Integer highSlaDays,
            Integer mediumSlaDays,
            Integer lowSlaDays,
            Double assetCriticalSlaMultiplier,
            Double assetHighSlaMultiplier,
            Double assetMediumSlaMultiplier,
            Double assetLowSlaMultiplier,
            Boolean autoCloseEnabled,
            String autoCloseAssetIdentifier,
            Integer autoCloseAfterDays,
            String findingGenerationMode,
            String findingsScoreConfig,
            Double agentAutoThreshold,
            Double agentReviewThreshold,
            Integer agentMaxConcurrent
    ) {
        this(
                criticalThreshold,
                highThreshold,
                criticalSlaDays,
                highSlaDays,
                mediumSlaDays,
                lowSlaDays,
                assetCriticalSlaMultiplier,
                assetHighSlaMultiplier,
                assetMediumSlaMultiplier,
                assetLowSlaMultiplier,
                autoCloseEnabled,
                autoCloseAssetIdentifier,
                autoCloseAfterDays,
                findingGenerationMode,
                findingsScoreConfig,
                agentAutoThreshold,
                agentReviewThreshold,
                agentMaxConcurrent,
                null,
                null,
                null,
                null,
                null,
                null,
                null
        );
    }
}
