-- migration-guard: platform-only
ALTER TABLE platform.ai_grid_policy_versions
    ADD COLUMN native_kinds_json jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE platform.ai_grid_policy_versions
    ADD COLUMN scope_resolution varchar(32) NOT NULL DEFAULT 'STATIC';
ALTER TABLE platform.ai_grid_policy_versions
    ADD CONSTRAINT ai_grid_policy_scope_resolution_check
    CHECK (scope_resolution IN ('STATIC','NATIVE_KIND_PLUS_STATIC'));

UPDATE platform.ai_grid_policy_versions
SET native_kinds_json = '["AWS_BEDROCK_AGENT"]'::jsonb
WHERE policy_id = 'AWS_BEDROCK_WEAK_GUARDRAIL' AND version = '2.0.0';

CREATE UNIQUE INDEX uk_ai_grid_one_published_policy_version
    ON platform.ai_grid_policy_versions (policy_id)
    WHERE lifecycle = 'PUBLISHED';

INSERT INTO platform.ai_grid_technology_versions
    (technology_id, version, display_name, provider, lifecycle, resource_families_json)
VALUES
    ('AZURE_AI_SERVICES', '1.0.0', 'Azure AI Services', 'AZURE', 'ACTIVE', '["AZURE_AI_ACCOUNTS","AZURE_DIAGNOSTIC_SETTINGS"]'),
    ('AZURE_AI_FOUNDRY', '1.0.0', 'Azure AI Foundry', 'AZURE', 'ACTIVE', '["AZURE_FOUNDRY_PROJECTS","AZURE_FOUNDRY_DEPLOYMENTS","AZURE_FOUNDRY_AGENTS","AZURE_FOUNDRY_AGENT_TOOLS"]'),
    ('AZURE_MACHINE_LEARNING', '1.0.0', 'Azure Machine Learning', 'AZURE', 'ACTIVE', '["AZURE_ML_WORKSPACES","AZURE_ML_MODELS","AZURE_ML_ENDPOINTS","AZURE_ML_DEPLOYMENTS","AZURE_ML_COMPUTE","AZURE_ML_JOBS","AZURE_ML_PIPELINES"]'),
    ('AZURE_AI_SEARCH', '1.0.0', 'Azure AI Search', 'AZURE', 'ACTIVE', '["AZURE_SEARCH_SERVICES","AZURE_SEARCH_INDEXES","AZURE_SEARCH_SKILLSETS","AZURE_SEARCH_INDEXERS","AZURE_SEARCH_DATA_SOURCES"]'),
    ('AZURE_BOT_SERVICE', '1.0.0', 'Azure Bot Service', 'AZURE', 'ACTIVE', '["AZURE_BOT_SERVICES","AZURE_BOT_CHANNELS","AZURE_BOT_IDENTITIES"]')
ON CONFLICT DO NOTHING;

INSERT INTO platform.ai_grid_technology_versions
    (technology_id, version, display_name, provider, lifecycle, resource_families_json)
VALUES ('UNMAPPED_AI_TECHNOLOGY', '1.0.0', 'Unmapped AI technology', 'UNKNOWN', 'ACTIVE', '[]')
ON CONFLICT DO NOTHING;

INSERT INTO platform.ai_grid_fact_definitions
    (fact_key, version, value_type, claim_semantics, allowed_evidence_classes_json,
     allowed_workflow_uses_json, default_max_age_seconds)
VALUES
    ('data.s3_public_access_configured','1.0.0','BOOLEAN','Provider configuration indicates that a knowledge-base S3 source is public.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('compute.lambda_url_auth_type_configured','1.0.0','STRING','Effective configured authentication type across agent action-group Lambda URLs.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.wildcard_permission_observed','1.0.0','BOOLEAN','A syntactic wildcard action was observed in the directly inspected execution-role policies.','["CONFIGURATION"]','["POSTURE_FINDING","EXPOSURE_HYPOTHESIS"]',86400),
    ('logging.model_invocation_enabled_configured','1.0.0','BOOLEAN','Bedrock model invocation logging is configured.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.local_auth_enabled_configured','1.0.0','BOOLEAN','Provider configuration permits key-based local authentication.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('logging.diagnostic_enabled_configured','1.0.0','BOOLEAN','An approved diagnostic logging destination is configured and enabled.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('agent.code_interpreter_enabled_configured','1.0.0','BOOLEAN','The agent configuration enables Code Interpreter.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.ml_endpoint_local_auth_enabled_configured','1.0.0','BOOLEAN','The Azure ML endpoint permits local key authentication.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.search_local_admin_auth_enabled_configured','1.0.0','BOOLEAN','Azure AI Search local admin-key authentication is enabled.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.search_data_source_non_identity_auth_observed','1.0.0','BOOLEAN','Authoritative configuration shows non-identity authentication for the Search data source.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.bot_password_without_managed_identity_observed','1.0.0','BOOLEAN','Bot password authentication is configured without an assigned managed identity.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('data.customer_managed_key_configured','1.0.0','BOOLEAN','Provider configuration declares customer-managed-key encryption.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('network.private_endpoint_count_configured','1.0.0','NUMBER','Number of configured private endpoint connections observed from provider configuration.','["CONFIGURATION"]','["POSTURE_FINDING","EXPOSURE_HYPOTHESIS"]',86400),
    ('owner.tag_candidate','1.0.0','OBJECT','Unverified ownership candidate derived from provider resource tags.','["CONFIGURATION"]','["POSTURE_FINDING","EXPOSURE_HYPOTHESIS"]',86400),
    ('agent.status_observed','1.0.0','STRING','Provider-reported lifecycle status for the AI agent.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400),
    ('identity.execution_role_present_configured','1.0.0','BOOLEAN','Agent configuration contains a non-empty execution role identifier.','["CONFIGURATION"]','["POSTURE_FINDING"]',86400)
ON CONFLICT DO NOTHING;

-- Publish only controls whose current collectors can normally produce exact verdict facts.
-- Search data-source authentication remains PREVIEW so its missing collection is visible without owner findings.
INSERT INTO platform.ai_grid_policy_versions (
    policy_id, version, name, description, severity, lifecycle, workflow_class, default_selection,
    artifact_types_json, native_kinds_json, required_resource_families_json, required_facts_json,
    predicate_json, reason_code, remediation, framework_mappings_json, scope_resolution,
    approved_by, approved_at, published_at
) VALUES
('AWS_BEDROCK_PUBLIC_KB_S3','2.0.0','Public knowledge-base S3 source','A Bedrock knowledge base uses a publicly accessible S3 source.','CRITICAL','PUBLISHED','POSTURE_FINDING','REQUIRED','["KNOWLEDGE_BASE"]','["AWS_BEDROCK_KNOWLEDGE_BASE"]','["BEDROCK_KNOWLEDGE_BASES","S3_EXPOSURE"]','[{"factKey":"data.s3_public_access_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"data.s3_public_access_configured","eq":true}','BEDROCK_KB_S3_PUBLIC','Block public access and restrict the bucket policy to the knowledge-base execution role.','{"OWASP_LLM_TOP_10":["LLM02","LLM08"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AWS_BEDROCK_UNAUTH_LAMBDA_URL','2.0.0','Unauthenticated action-group Lambda URL','An agent action group exposes a Lambda URL without IAM authentication.','CRITICAL','PUBLISHED','POSTURE_FINDING','REQUIRED','["AI_AGENT"]','["AWS_BEDROCK_AGENT"]','["BEDROCK_AGENTS","LAMBDA_URLS"]','[{"factKey":"compute.lambda_url_auth_type_configured","valueType":"STRING","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"compute.lambda_url_auth_type_configured","eq":"NONE"}','BEDROCK_LAMBDA_URL_UNAUTHENTICATED','Require AWS_IAM authentication or remove the function URL.','{"OWASP_LLM_TOP_10":["LLM06"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AWS_BEDROCK_WILDCARD_AGENT_ROLE','2.0.0','Wildcard agent execution-role actions','A syntactic wildcard action was observed in the agent execution role.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["AI_AGENT"]','["AWS_BEDROCK_AGENT"]','["BEDROCK_AGENTS","IAM_GLOBAL"]','[{"factKey":"identity.wildcard_permission_observed","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.wildcard_permission_observed","eq":true}','BEDROCK_AGENT_ROLE_WILDCARD','Replace wildcard actions with minimum required actions and resources.','{"OWASP_LLM_TOP_10":["LLM06","LLM08"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AWS_BEDROCK_INVOCATION_LOGGING_DISABLED','2.0.0','Bedrock invocation logging disabled','Model invocation logging is disabled.','MEDIUM','PUBLISHED','POSTURE_FINDING','ENABLED','["ACCOUNT_CONFIGURATION"]','["AWS_BEDROCK_INVOCATION_LOGGING"]','["BEDROCK_INVOCATION_LOGGING"]','[{"factKey":"logging.model_invocation_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"logging.model_invocation_enabled_configured","eq":false}','BEDROCK_INVOCATION_LOGGING_DISABLED','Enable encrypted Bedrock model invocation logging.','{"OWASP_LLM_TOP_10":["LLM02"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_AI_UNRESTRICTED_PUBLIC_ACCESS','2.0.0','Unrestricted Azure AI public access','A managed Azure AI resource permits unrestricted public network access.','CRITICAL','PUBLISHED','POSTURE_FINDING','REQUIRED','["OTHER_AI_ARTIFACT"]','["AZURE_AI_ACCOUNTS","AZURE_ML_WORKSPACES","AZURE_SEARCH_SERVICES"]','[]','[{"factKey":"network.public_access_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"network.public_access_configured","eq":true}','AZURE_AI_UNRESTRICTED_PUBLIC_ACCESS','Disable public access or restrict network ACLs and use approved private endpoints.','{"OWASP_LLM_TOP_10":["LLM02","LLM06"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_AI_LOCAL_AUTH_ENABLED','2.0.0','Azure AI local authentication enabled','An Azure AI account permits key-based local authentication.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["OTHER_AI_ARTIFACT"]','["AZURE_AI_ACCOUNTS"]','[]','[{"factKey":"identity.local_auth_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.local_auth_enabled_configured","eq":true}','AZURE_AI_LOCAL_AUTH_ENABLED','Disable local authentication and require Microsoft Entra identities.','{"OWASP_LLM_TOP_10":["LLM06"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_AI_DIAGNOSTIC_LOGGING_DISABLED','2.0.0','Azure AI diagnostic logging disabled','An Azure AI account has no enabled diagnostic-log destination.','MEDIUM','PUBLISHED','POSTURE_FINDING','ENABLED','["OTHER_AI_ARTIFACT"]','["AZURE_AI_ACCOUNTS"]','["AZURE_DIAGNOSTIC_SETTINGS"]','[{"factKey":"logging.diagnostic_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"logging.diagnostic_enabled_configured","eq":false}','AZURE_AI_DIAGNOSTIC_LOGGING_DISABLED','Enable diagnostic logs to an approved destination.','{"OWASP_LLM_TOP_10":["LLM02"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_FOUNDRY_AGENT_CODE_INTERPRETER_ENABLED','2.0.0','Foundry agent Code Interpreter enabled','A Foundry agent enables Code Interpreter.','HIGH','PUBLISHED','POSTURE_FINDING','PREVIEW','["AI_AGENT"]','["AZURE_FOUNDRY_AGENTS"]','[]','[{"factKey":"agent.code_interpreter_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"agent.code_interpreter_enabled_configured","eq":true}','AZURE_FOUNDRY_CODE_INTERPRETER_ENABLED','Disable Code Interpreter unless explicitly approved.','{"OWASP_LLM_TOP_10":["LLM06"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_ML_ENDPOINT_LOCAL_AUTH_ENABLED','2.0.0','Azure ML endpoint local authentication enabled','An Azure ML endpoint permits local key authentication.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["OTHER_AI_ARTIFACT"]','["AZURE_ML_ENDPOINTS"]','[]','[{"factKey":"identity.ml_endpoint_local_auth_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.ml_endpoint_local_auth_enabled_configured","eq":true}','AZURE_ML_ENDPOINT_LOCAL_AUTH_ENABLED','Require Microsoft Entra authentication.','{"OWASP_LLM_TOP_10":["LLM06"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_SEARCH_LOCAL_ADMIN_AUTH_ENABLED','2.0.0','Azure AI Search local admin authentication enabled','An Azure AI Search service permits local admin-key authentication.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["OTHER_AI_ARTIFACT"]','["AZURE_SEARCH_SERVICES"]','[]','[{"factKey":"identity.search_local_admin_auth_enabled_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.search_local_admin_auth_enabled_configured","eq":true}','AZURE_SEARCH_LOCAL_ADMIN_AUTH_ENABLED','Disable local authentication and use Entra RBAC.','{"OWASP_LLM_TOP_10":["LLM06","LLM08"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_SEARCH_DATA_SOURCE_NON_IDENTITY_AUTH','2.0.0','Azure AI Search data source does not use identity authentication','Search data-source authentication is not identity based.','HIGH','PUBLISHED','POSTURE_FINDING','PREVIEW','["OTHER_AI_ARTIFACT"]','["AZURE_SEARCH_DATA_SOURCES"]','[]','[{"factKey":"identity.search_data_source_non_identity_auth_observed","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.search_data_source_non_identity_auth_observed","eq":true}','AZURE_SEARCH_NON_IDENTITY_AUTH','Use a managed identity for the Search data-source connection.','{"OWASP_LLM_TOP_10":["LLM06","LLM08"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_BOT_PASSWORD_AUTH_WITHOUT_MANAGED_IDENTITY','2.0.0','Azure Bot password authentication without managed identity','An Azure Bot uses password authentication without a managed identity.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["AI_AGENT"]','["AZURE_BOT_SERVICES"]','["AZURE_BOT_IDENTITIES"]','[{"factKey":"identity.bot_password_without_managed_identity_observed","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"identity.bot_password_without_managed_identity_observed","eq":true}','AZURE_BOT_PASSWORD_WITHOUT_MANAGED_IDENTITY','Assign a managed identity and remove password credentials.','{"OWASP_LLM_TOP_10":["LLM06"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AWS_BEDROCK_GUARDRAIL_NOT_ATTACHED','1.0.0','No guardrail attached to Bedrock agent','A Bedrock agent has no configured guardrail association.','HIGH','PUBLISHED','POSTURE_FINDING','ENABLED','["AI_AGENT"]','["AWS_BEDROCK_AGENT"]','["BEDROCK_AGENTS"]','[{"factKey":"bedrock.agent.guardrail_attached_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"bedrock.agent.guardrail_attached_configured","eq":false}','BEDROCK_GUARDRAIL_NOT_ATTACHED','Attach an approved Bedrock guardrail to every production agent path.','{"OWASP_LLM_TOP_10":["LLM01","LLM05"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AWS_BEDROCK_AGENT_INACTIVE_OR_ROLE_MISSING','1.0.0','Bedrock agent inactive or missing execution role','The agent is not prepared or has no configured execution role.','MEDIUM','PUBLISHED','POSTURE_FINDING','PREVIEW','["AI_AGENT"]','["AWS_BEDROCK_AGENT"]','["BEDROCK_AGENTS"]','[{"factKey":"agent.status_observed","valueType":"STRING","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400},{"factKey":"identity.execution_role_present_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"any":[{"fact":"agent.status_observed","neq":"PREPARED"},{"fact":"identity.execution_role_present_configured","eq":false}]}','BEDROCK_AGENT_INACTIVE_OR_ROLE_MISSING','Prepare the agent and configure its least-privileged execution role.','{"OWASP_LLM_TOP_10":["LLM06"]}','STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_AI_PRIVATE_ENDPOINT_MISSING','1.0.0','Azure AI private endpoint missing','No private endpoint connection is configured for the managed AI resource.','MEDIUM','PUBLISHED','POSTURE_FINDING','PREVIEW','["OTHER_AI_ARTIFACT"]','["AZURE_AI_ACCOUNTS"]','[]','[{"factKey":"network.private_endpoint_count_configured","valueType":"NUMBER","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"network.private_endpoint_count_configured","eq":0}','AZURE_AI_PRIVATE_ENDPOINT_MISSING','Configure an approved private endpoint and restrict public network access.','{"OWASP_LLM_TOP_10":["LLM02"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now()),
('AZURE_AI_CUSTOMER_MANAGED_KEY_MISSING','1.0.0','Azure AI customer-managed-key encryption missing','The Azure AI account is not configured with a customer-managed encryption key.','MEDIUM','PUBLISHED','POSTURE_FINDING','ENABLED','["OTHER_AI_ARTIFACT"]','["AZURE_AI_ACCOUNTS"]','[]','[{"factKey":"data.customer_managed_key_configured","valueType":"BOOLEAN","evidenceClasses":["CONFIGURATION"],"maxAgeSeconds":86400}]','{"fact":"data.customer_managed_key_configured","eq":false}','AZURE_AI_CUSTOMER_MANAGED_KEY_MISSING','Configure encryption with a customer-managed key in an approved Key Vault.','{"OWASP_LLM_TOP_10":["LLM02","LLM03"]}','NATIVE_KIND_PLUS_STATIC','ai-grid-r1-bootstrap',now(),now())
ON CONFLICT DO NOTHING;
