-- migration-guard: platform-only
CREATE TABLE platform.ai_grid_resource_family_definitions (
    resource_family varchar(128) PRIMARY KEY,
    provider varchar(32) NOT NULL CHECK (provider IN ('AWS','AZURE','MULTI_CLOUD')),
    scope_semantics varchar(32) NOT NULL CHECK (scope_semantics IN ('REGIONAL','ACCOUNT_GLOBAL')),
    lifecycle varchar(32) NOT NULL DEFAULT 'ACTIVE' CHECK (lifecycle IN ('ACTIVE','RETIRED')),
    description text NOT NULL
);

CREATE TABLE platform.ai_grid_relationship_definitions (
    relationship_type varchar(128) PRIMARY KEY,
    source varchar(64) NOT NULL,
    directional boolean NOT NULL DEFAULT true,
    lifecycle varchar(32) NOT NULL DEFAULT 'ACTIVE' CHECK (lifecycle IN ('ACTIVE','RETIRED')),
    description text NOT NULL
);

INSERT INTO platform.ai_grid_resource_family_definitions
    (resource_family,provider,scope_semantics,description)
VALUES
 ('BEDROCK_AGENTS','AWS','REGIONAL','Bedrock Agents discovery.'),
 ('BEDROCK_KNOWLEDGE_BASES','AWS','REGIONAL','Bedrock knowledge base discovery.'),
 ('BEDROCK_DATA_SOURCES','AWS','REGIONAL','Bedrock data-source discovery.'),
 ('BEDROCK_DATA_STORES','AWS','REGIONAL','Bedrock data-store discovery.'),
 ('AWS_AGENTCORE_GATEWAYS','AWS','REGIONAL','AgentCore gateway discovery.'),
 ('AWS_AGENTCORE_GATEWAY_TARGETS','AWS','REGIONAL','AgentCore target discovery.'),
 ('BEDROCK_GUARDRAILS','AWS','REGIONAL','Bedrock Guardrails discovery.'),
 ('BEDROCK_INVOCATION_LOGGING','AWS','REGIONAL','Bedrock invocation logging discovery.'),
 ('BEDROCK_DEPLOYABLE_MODELS','AWS','REGIONAL','Bedrock model discovery.'),
 ('BEDROCK_INFERENCE_PROFILES','AWS','REGIONAL','Bedrock inference-profile discovery.'),
 ('BEDROCK_MODEL_CUSTOMIZATION_JOBS','AWS','REGIONAL','Bedrock customization-job discovery.'),
 ('BEDROCK_PROMPTS','AWS','REGIONAL','Bedrock prompt metadata discovery.'),
 ('BEDROCK_FLOWS','AWS','REGIONAL','Bedrock flow discovery.'),
 ('SAGEMAKER_DOMAINS','AWS','REGIONAL','SageMaker domain discovery.'),
 ('SAGEMAKER_SPACES','AWS','REGIONAL','SageMaker space discovery.'),
 ('SAGEMAKER_MODEL_REGISTRY','AWS','REGIONAL','SageMaker registry discovery.'),
 ('SAGEMAKER_ENDPOINTS','AWS','REGIONAL','SageMaker endpoint discovery.'),
 ('SAGEMAKER_ENDPOINT_CONFIGURATIONS','AWS','REGIONAL','SageMaker endpoint-configuration discovery.'),
 ('SAGEMAKER_JOBS','AWS','REGIONAL','SageMaker job discovery.'),
 ('SAGEMAKER_PIPELINES','AWS','REGIONAL','SageMaker pipeline discovery.'),
 ('SAGEMAKER_COMPUTE','AWS','REGIONAL','SageMaker compute discovery.'),
 ('SAGEMAKER_EXECUTION_ROLES','AWS','ACCOUNT_GLOBAL','SageMaker execution-role discovery.'),
 ('SAGEMAKER_NETWORKING','AWS','REGIONAL','SageMaker networking discovery.'),
 ('LAMBDA_URLS','AWS','REGIONAL','Lambda URL discovery.'),
 ('S3_EXPOSURE','AWS','REGIONAL','S3 exposure discovery.'),
 ('AWS_MACIE_PII','AWS','REGIONAL','Amazon Macie PII classification discovery.'),
 ('IAM_GLOBAL','AWS','ACCOUNT_GLOBAL','IAM discovery.'),
 ('AZURE_AI_ACCOUNTS','AZURE','REGIONAL','Azure AI account discovery.'),
 ('AZURE_FOUNDRY_PROJECTS','AZURE','REGIONAL','Azure Foundry project discovery.'),
 ('AZURE_FOUNDRY_DEPLOYMENTS','AZURE','REGIONAL','Azure Foundry deployment discovery.'),
 ('AZURE_RAI_POLICIES','AZURE','REGIONAL','Azure RAI policy discovery.'),
 ('AZURE_FOUNDRY_AGENTS','AZURE','REGIONAL','Azure Foundry agent discovery.'),
 ('AZURE_FOUNDRY_AGENT_TOOLS','AZURE','REGIONAL','Azure Foundry tool discovery.'),
 ('AZURE_ML_WORKSPACES','AZURE','REGIONAL','Azure ML workspace discovery.'),
 ('AZURE_ML_MODELS','AZURE','REGIONAL','Azure ML model discovery.'),
 ('AZURE_ML_ENDPOINTS','AZURE','REGIONAL','Azure ML endpoint discovery.'),
 ('AZURE_ML_DEPLOYMENTS','AZURE','REGIONAL','Azure ML deployment discovery.'),
 ('AZURE_ML_COMPUTE','AZURE','REGIONAL','Azure ML compute discovery.'),
 ('AZURE_ML_JOBS','AZURE','REGIONAL','Azure ML job discovery.'),
 ('AZURE_ML_PIPELINES','AZURE','REGIONAL','Azure ML pipeline discovery.'),
 ('AZURE_SEARCH_SERVICES','AZURE','REGIONAL','Azure AI Search service discovery.'),
 ('AZURE_SEARCH_INDEXES','AZURE','REGIONAL','Azure AI Search index discovery.'),
 ('AZURE_SEARCH_SKILLSETS','AZURE','REGIONAL','Azure AI Search skillset discovery.'),
 ('AZURE_SEARCH_INDEXERS','AZURE','REGIONAL','Azure AI Search indexer discovery.'),
 ('AZURE_SEARCH_DATA_SOURCES','AZURE','REGIONAL','Azure AI Search data-source discovery.'),
 ('AZURE_SEARCH_KNOWLEDGE_BASES','AZURE','REGIONAL','Azure AI Search knowledge-base discovery.'),
 ('AZURE_SEARCH_KNOWLEDGE_SOURCES','AZURE','REGIONAL','Azure AI Search knowledge-source discovery.'),
 ('AZURE_BOT_SERVICES','AZURE','ACCOUNT_GLOBAL','Azure Bot service discovery.'),
 ('AZURE_BOT_CHANNELS','AZURE','ACCOUNT_GLOBAL','Azure Bot channel discovery.'),
 ('AZURE_BOT_IDENTITIES','AZURE','ACCOUNT_GLOBAL','Azure Bot identity discovery.'),
 ('AZURE_DIAGNOSTIC_SETTINGS','AZURE','REGIONAL','Azure diagnostic-settings discovery.'),
 ('AZURE_RBAC_GLOBAL','AZURE','ACCOUNT_GLOBAL','Azure RBAC discovery.'),
 ('AZURE_RBAC_ASSIGNMENTS','AZURE','REGIONAL','Azure RBAC assignment discovery.'),
 ('AZURE_PURVIEW_CLASSIFICATION','AZURE','REGIONAL','Azure Purview classification discovery.')
ON CONFLICT (resource_family) DO NOTHING;

INSERT INTO platform.ai_grid_relationship_definitions (relationship_type,source,description)
VALUES
 ('USES_MODEL','OBSERVATION_V1','Artifact uses a model.'),
 ('USES_GUARDRAIL','OBSERVATION_V1','Artifact uses a guardrail.'),
 ('USES_KNOWLEDGE_BASE','OBSERVATION_V1','Artifact uses a knowledge base.'),
 ('USES_DATA_SOURCE','OBSERVATION_V1','Artifact uses a data source.'),
 ('BACKED_BY_DATA_STORE','OBSERVATION_V1','Artifact is backed by a data store.'),
 ('USES_SEARCH_INDEX','OBSERVATION_V1','Artifact uses a search index.'),
 ('EXPOSES_MCP','OBSERVATION_V1','Artifact exposes MCP.'),
 ('CONNECTS_TO_MCP','OBSERVATION_V1','Artifact connects to MCP.'),
 ('CONTAINS_MCP_TARGET','OBSERVATION_V1','Gateway contains an MCP target.'),
 ('ROUTES_TO','OBSERVATION_V1','Artifact routes to another artifact.'),
 ('INVOKES_LAMBDA','OBSERVATION_V1','Artifact invokes Lambda.'),
 ('ASSUMES_ROLE','OBSERVATION_V1','Artifact assumes a role.'),
 ('READS_FROM_S3','OBSERVATION_V1','Artifact reads from S3.'),
 ('LOGS_TO','OBSERVATION_V1','Artifact logs to a destination.'),
 ('SUPERVISES_AGENT','OBSERVATION_V1','Artifact supervises an agent.'),
 ('CONTAINS_PROJECT','OBSERVATION_V1','Artifact contains a project.'),
 ('DEPLOYS_MODEL','OBSERVATION_V1','Artifact deploys a model.'),
 ('USES_TOOL','OBSERVATION_V1','Artifact uses a tool.'),
 ('USES_MANAGED_IDENTITY','OBSERVATION_V1','Artifact uses managed identity.'),
 ('HAS_PRIVATE_ENDPOINT','OBSERVATION_V1','Artifact has a private endpoint.'),
 ('USES_KEY_VAULT_KEY','OBSERVATION_V1','Artifact uses a Key Vault key.'),
 ('CONTAINS_RESOURCE','OBSERVATION_V1','Artifact contains a resource.'),
 ('HAS_DEPLOYMENT','OBSERVATION_V1','Artifact has a deployment.'),
 ('RUNS_PIPELINE','OBSERVATION_V1','Artifact runs a pipeline.'),
 ('HAS_CHANNEL','OBSERVATION_V1','Artifact has a channel.'),
 ('HAS_ROLE_ASSIGNMENT','OBSERVATION_V1','Artifact has a role assignment.'),
 ('CONTAINS','OBSERVATION_V1','Artifact contains another artifact.'),
 ('USES_EXECUTION_ROLE','OBSERVATION_V1','Artifact uses an execution role.'),
 ('USES_NETWORK','OBSERVATION_V1','Artifact uses a network.'),
 ('USES_ENDPOINT_CONFIGURATION','OBSERVATION_V1','Artifact uses endpoint configuration.'),
 ('PRODUCES_MODEL','OBSERVATION_V1','Artifact produces a model.'),
 ('USES_DATA_CONNECTION','OBSERVATION_V1','Artifact uses a data connection.'),
 ('READS_FROM_STORAGE_ACCOUNT','OBSERVATION_V1','Artifact reads from a storage account.'),
 ('DIRECT_PROVIDER_RELATIONSHIP','AI_GRID_GRAPH','Governed one-hop graph evaluation profile.')
ON CONFLICT (relationship_type) DO NOTHING;
