-- migration-guard: platform-only
-- Phase 1 shipping is source-controlled.  Tenant evidence is deliberately not
-- consulted while installing, publishing, distributing, or pinning a package.

CREATE TABLE IF NOT EXISTS platform.ai_grid_policy_rollouts (
    id uuid PRIMARY KEY,
    release_id varchar(128) NOT NULL,
    release_type varchar(64) NOT NULL,
    policy_id varchar(128) NOT NULL,
    previous_version varchar(32),
    new_version varchar(32) NOT NULL,
    package_digest varchar(64) NOT NULL,
    distribution_snapshot_json jsonb NOT NULL,
    status varchar(32) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    UNIQUE (release_id, policy_id, new_version),
    CHECK (release_type IN ('INITIAL_CATALOG','POLICY_VERSION','REPLACEMENT')),
    CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED'))
);

CREATE TABLE IF NOT EXISTS platform.ai_grid_policy_rollout_tasks (
    id uuid PRIMARY KEY,
    rollout_id uuid NOT NULL REFERENCES platform.ai_grid_policy_rollouts(id) ON DELETE CASCADE,
    tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
    status varchar(32) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    next_retry_at timestamptz,
    source_snapshot_run_id uuid,
    assessment_run_id uuid,
    failure_detail text,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (rollout_id, tenant_id),
    CHECK (status IN ('PENDING','PROCESSING','WAITING_FOR_SNAPSHOT','COMPLETED','FAILED'))
);
CREATE INDEX IF NOT EXISTS idx_ai_grid_policy_rollout_tasks_claim
    ON platform.ai_grid_policy_rollout_tasks (status, next_retry_at, created_at);

-- Promote every bundled AGCF package. V76/V88/V89 remain immutable; V91 is the
-- reviewed forward-only shipping decision and pins distribution to its digest.
UPDATE platform.ai_grid_policy_versions
   SET lifecycle = 'PUBLISHED',
       approved_by = coalesce(approved_by, 'ai-grid-package-compiler'),
       approved_at = coalesce(approved_at, now()),
       published_at = coalesce(published_at, now())
 WHERE policy_id LIKE 'AGCF-%'
   AND package_source_ref LIKE 'policy-packages/agcf/%'
   AND lifecycle IN ('DRAFT','VALIDATED');

UPDATE platform.ai_grid_policy_versions SET default_selection = 'ENABLED'
 WHERE policy_id LIKE 'AGCF-%' AND default_selection = 'PREVIEW';

-- generated-manifest-digest-bindings:start
-- Generated by scripts/compile-ai-grid-phase1.mjs. Do not hand-edit package rows.
WITH shipped(policy_id,version,package_digest) AS (VALUES
('AGCF-AWS-001','1.0.0','57781735b507f8f284472af507020181380e71ae41716fd70ba84a904e2697b1'),
('AGCF-AWS-002','1.0.0','c12b96252a146d3e49dfb137130bf02888d2aafd01490fb94cf97f72e30b6a2a'),
('AGCF-AWS-003','1.0.0','9feb9672faee1c0cbac3301be20f69bfde67b30cd8373932260fe36404e32487'),
('AGCF-AWS-004','1.0.0','07cd28465e7064470b624fb880f668fb85d1378748ecc5c7170e84a4f342d09f'),
('AGCF-AWS-005','1.0.0','23b8b88e1f39b1027b06523d80f50a0d04c561a70c20892935f3de39f08c590d'),
('AGCF-AWS-006','1.0.0','7bb3c448e05ef599a309356a41c30bbd6840754861453cf7cf1919d61d121c2d'),
('AGCF-AWS-007','1.0.0','5c190b1ba579381d98752ed9bfe778ee72726f322a33ea9ae746ae4d2c666586'),
('AGCF-AWS-008','1.0.0','a1ca007efa0d57ff15657a8c0f5e319cf29e3594083f7b25ff53f1305652ee67'),
('AGCF-AWS-009','1.0.0','b0e9bd0238a1a76adb5962d9a50752c9d00df4c753b351ebcf37123500f79a6c'),
('AGCF-AWS-010','1.0.0','2085139054fde1a89dd39349c5246be8659b3f86e16e5df8bd2c879da5d4c02e'),
('AGCF-AWS-011','1.0.0','9ca94d96b62255aff0b50627bce8a40a93b8958b1a28868c29eab35127d480da'),
('AGCF-AWS-012','1.0.0','07cc0a7ce59e1691a3b05fb5b35ef25533a91dda201a96423108429edbea5d40'),
('AGCF-AWS-013','1.0.0','ad4f6868de61f569dc70460d3c146a948aee1191c660cc189800d546f02cdd3c'),
('AGCF-AWS-014','1.0.0','7dcf639821e689065acde25d6ee6e641b80e01eb473f03b6d4ef11ae65b623c0'),
('AGCF-AWS-015','1.0.0','e9a5a7eed7500f691aec17b5ef623e0e6dfdac7c55c3e54c01f93633c930b84a'),
('AGCF-AWS-016','1.0.0','63b237f362088e6e18fe80b313c6a2d0f8cbe1c8b72f7b0d523251097e822d75'),
('AGCF-AWS-017','1.0.0','92032a2275adb81da31144fba77922b2466e398dece88862760f29b84911c799'),
('AGCF-AWS-018','1.0.0','33027bed112f7fb9e19f2f532c04a7996dc105c76b9aa931e859d72aa797b927'),
('AGCF-AWS-019','1.0.0','c8ce30888a018c8442570d5cc4f803285682a6cf8bd81886a30fa13172c7edcd'),
('AGCF-AWS-020','1.0.0','5600cba4b91ce8eb887aa61252cd19620274a3818f3df6ac9c5338b88dde04ed'),
('AGCF-AWS-021','1.0.0','a2f3b5aa79d35ca337633c73ecb65635ce29f2feba47945ed63449f4408e1391'),
('AGCF-AWS-022','1.0.0','17b466fce5a0933cd2f29a16ba150570968b5bd7bdbb7c100fe9247c53b3effe'),
('AGCF-AWS-023','1.0.0','46bd7553eb526bbdc0020e2471c68d8e708897765a5a680e923790778db323b6'),
('AGCF-AWS-024','1.0.0','32493d9bac26e8c6392bc9e0be84bb475257836e4b95e8cb3a33b435bd483a69'),
('AGCF-AWS-025','1.0.0','8d45578380aee8ad28aa11817b4fac1e767322c216a0c25b859d95bd12910c34'),
('AGCF-AWS-026','1.0.0','00f9dbf74b2df8503837a8d898285bbb83ef77008ef19f449d0f32ab47d81e81'),
('AGCF-AWS-027','1.0.0','60357eaee299c5f144c7c9979655d44f81fae435acf0b218186aa5045ab4a331'),
('AGCF-AWS-028','1.0.0','7790daf45be65ae53c8e236df812d4015709b651405a3103726017662f775153'),
('AGCF-AWS-029','1.0.0','c0591f1280f470e380698f3ad97e4162b314d3eff20988f819d57be51f76e429'),
('AGCF-AWS-030','1.0.0','136d320464e1b73b69caa7aefebd72e73caf94328c986bc78fc66cf7813a09ae'),
('AGCF-AWS-031','1.0.0','2a234e76ad25868156e3292f6c599149fbefd375585273e6b5d8fc7c2c75fe55'),
('AGCF-AWS-032','1.0.0','cd0298bd26d3ae64f730b55da8ccccdcd4a4cdb81ef4913b8e775b1f9f25f202'),
('AGCF-AWS-033','1.0.0','9723cada991dc4c9de96f16e50e67fd13b320f5d61294c96a7fa11d45b5fe382'),
('AGCF-AWS-034','1.0.0','468d4f2f64d16d755e2268d4817e3743b40bdbec76ed2ff447b2482c88d3ee24'),
('AGCF-AWS-035','1.0.0','d4b365402012676f0a0250ba30c6570a2b6ecb1dbe4b3c460e123fad162313cf'),
('AGCF-AWS-036','1.0.0','fc02fa9441435d43ae05ac28673c413059567c4eb3106fec0fe0e5230b0ff9c2'),
('AGCF-AWS-037','1.0.0','eb83fa2afdb801fd67a1cf37c3b6214be2b19774e3abd06ca146ed3315739c21'),
('AGCF-AWS-038','1.0.0','377f6069bef60525f43d1fe5bda8ff8d5cde4334fd355937a58378efaa371967'),
('AGCF-AZR-001','1.0.0','046bbffeaa50c65541cdb7742dcf4ced919d025579045d2007af0d84092704e2'),
('AGCF-AZR-002','1.0.0','6439276140620f364748a6c4dff16c7f68c4fa8934336fa3b0c0686c0f481608'),
('AGCF-AZR-003','1.0.0','df812e74b06ec3d28df42cccd2c4e6394a03e8650a76b24ce1a12cfe016eb47d'),
('AGCF-AZR-004','1.0.0','7cdc37529db58523b5fbe9c8bf7a8b1c77884d147533ba8c384c623b51d4bcc1'),
('AGCF-AZR-005','1.0.0','bedc94b31e40aa4f55664b99b7dacacd73667a482068f3e36e2daf01bfb54aaf'),
('AGCF-AZR-006','1.0.0','2af6dcd38095ab9090be5ff78990ccf8afba8042ea693603eaa08083f46dfd3b'),
('AGCF-AZR-007','1.0.0','10f2a258b173eb96c6f05e9b63fafbe4dd5dd3db8bf3a52bfdac51e8fb62e593'),
('AGCF-AZR-008','1.0.0','ece3b78208cfaae29c247c8ff78a1554f387b1c94d8617ad59677f64d2e5f2fb'),
('AGCF-AZR-009','1.0.0','98eb727f433b21c7bbb7966cd8c7a3bd384ad692845fbe6775e9b1fe264b6e7b'),
('AGCF-AZR-010','1.0.0','a54b33061982f59777b5aa68c4ed9f7b06b960eaf56eee683e4afe5e317c5dea'),
('AGCF-AZR-011','1.0.0','065cf0952abfc7d4a84f26f7e9a353fcf52d5451d9d09c4355c710fae4d49bc6'),
('AGCF-AZR-012','1.0.0','664aca53cd6c3ed7f437dfa42cca2372280a3066797a9a4fba7c98c8cd45f79a'),
('AGCF-AZR-013','1.0.0','9e824a72c65ea1ba5c97d77caa043cef4da26951a62f5bc5716669f4f50ff4d5'),
('AGCF-AZR-014','1.0.0','c17014f0ca16723456cc795d8b04c52f784298d79f1f3254837b39e1c341c16e'),
('AGCF-AZR-015','1.0.0','52a3ebeb4e58935dc7b1a6b5837b1319bf26d98d4c9c1532cc2ccf84ab06450c'),
('AGCF-AZR-016','1.0.0','3071eec263ebb4a9d468da373cd2d7d6aa2d80925277828f7ac069de7fc72a4f'),
('AGCF-AZR-017','1.0.0','2616adf6abb03e4fcf61349130285dceb34122f2198da2ca35f52ac254f39359'),
('AGCF-AZR-018','1.0.0','999807ed8ca6bd7ba48349624be80bb44b4ea70e33a9c6a8f12ebff3550e7184'),
('AGCF-AZR-019','1.0.0','d444cf2eabef606ab116a7bab9dd4f112b8c3e7f91d31e90151540f3badecc4b'),
('AGCF-AZR-020','1.0.0','055a6129236c68ef0997e2486d3b1aed1ca25be2fe376167ea34e4d9a6afb97a'),
('AGCF-AZR-021','1.0.0','e4e301f70db0173986a0064c08067a528c8956e2703697e6f6101760c5492250'),
('AGCF-AZR-022','1.0.0','5ed0d2f2958c4c71f29e16601ef01bebf77ae8905f0f42954c64d0025d832108'),
('AGCF-AZR-023','1.0.0','e50b5f26ed18870f2723e9ea177effab94e25cbf0dad9f501c386ae5b10a075f'),
('AGCF-AZR-024','1.0.0','74d0fd1107a27fbee282e4fe9a2e2b99977668adc79715b277ca0ca6abf1520a'),
('AGCF-AZR-025','1.0.0','ca67ac614ec02a61f27d2bb4118bd51f0132c5f662421b22825612006b7e87c8'),
('AGCF-AZR-026','1.0.0','534500676194bbde05c1c2071fb22612c101a7b7994f6f8a1c793754a854810c'),
('AGCF-AZR-027','1.0.0','31946f2b9733f78d7a02865edf162a74ef6c295e9adf19832466e9981c3bb833'),
('AGCF-AZR-028','1.0.0','a1b5d9432ee0554b15446b519ceefc2100e4010fb0b2cb82f615fef949061233'),
('AGCF-AZR-029','1.0.0','e484838e945bd0df97f75305668091f5397e4f39f6a991505513a6ba43f92884'),
('AGCF-AZR-030','1.0.0','114068db61bb49bcbee8f502f4608b8b384b6dd7336cdbf679cd6464eb24fb95'),
('AGCF-AZR-031','1.0.0','9bcaf2cc4a18af2a5f7d9234c5ba8606a12b27eda294d10220cdd3dc8db272a1'),
('AGCF-AZR-032','1.0.0','0f05267df3a5c72b4210721794a71b91560e321c3bce4c12926cad6aed51e62c'),
('AGCF-XSP-001','1.0.0','e94674a32c10d0c6002826434944f523f1e1180139134b4be21e5a34f1ccfa9a'),
('AGCF-XSP-002','1.0.0','c5924043d588c67f2031ac30ebe4df12f9b569ed35815fd3f8bc3f2e9e687fc2'),
('AGCF-XSP-003','1.0.0','dc97f04ed54742f22c6508c48895137b030a4dbcd5bd1b9ba62ee841b53876db'),
('AGCF-XSP-004','1.0.0','10d8195e99d426cfd7e7de6205af391fb95aed50c2136efeacf4ac6054be909d'),
('AGCF-XSP-005','1.0.0','c91296a7958e37a3d29f78d08304b5310d06f9cb8883ef35851e2b44da4d75bc'),
('AGCF-XSP-006','1.0.0','d7907c4de2724d819152f823c92799c27d7bc977b79bd23fe4f2fa43f41162c1')
)
UPDATE platform.ai_grid_policy_versions policy
   SET package_digest = shipped.package_digest
  FROM shipped
 WHERE policy.policy_id = shipped.policy_id
   AND policy.version = shipped.version
   AND policy.package_source_ref LIKE 'policy-packages/agcf/%';
-- generated-manifest-digest-bindings:end

INSERT INTO platform.ai_grid_policy_distribution
    (policy_id, available, default_selection, rollout_stage, canary_tenant_ids_json, pinned_version, updated_by)
SELECT p.policy_id, true, p.default_selection, 'GENERAL_AVAILABILITY', '[]'::jsonb, p.version,
       'ai-grid-package-compiler'
  FROM platform.ai_grid_policy_versions p
 WHERE p.policy_id LIKE 'AGCF-%'
   AND p.package_source_ref LIKE 'policy-packages/agcf/%'
   AND p.lifecycle = 'PUBLISHED'
ON CONFLICT (policy_id) DO UPDATE
   SET available = true,
       default_selection = excluded.default_selection,
       rollout_stage = 'GENERAL_AVAILABILITY',
       canary_tenant_ids_json = '[]'::jsonb,
       pinned_version = excluded.pinned_version,
       updated_by = excluded.updated_by,
       updated_at = now();

INSERT INTO platform.ai_grid_policy_rollouts
    (id, release_id, release_type, policy_id, previous_version, new_version, package_digest, distribution_snapshot_json, status, completed_at)
SELECT md5('AGCF_PHASE_1_INITIAL:' || p.policy_id || ':' || p.version)::uuid,
       'AGCF_PHASE_1_INITIAL', 'INITIAL_CATALOG', p.policy_id, null, p.version, p.package_digest,
       jsonb_build_object('available', d.available, 'defaultSelection', d.default_selection,
                          'rolloutStage', d.rollout_stage, 'canaryTenantIds', d.canary_tenant_ids_json,
                          'pinnedVersion', d.pinned_version),
       'PENDING', null
  FROM platform.ai_grid_policy_versions p
  JOIN platform.ai_grid_policy_distribution d ON d.policy_id = p.policy_id
 WHERE p.policy_id LIKE 'AGCF-%'
   AND p.package_source_ref LIKE 'policy-packages/agcf/%'
   AND p.lifecycle = 'PUBLISHED'
ON CONFLICT (release_id, policy_id, new_version) DO NOTHING;

INSERT INTO platform.ai_grid_policy_rollout_tasks (id, rollout_id, tenant_id)
SELECT md5(r.id::text || ':' || t.id::text)::uuid, r.id, t.id
  FROM platform.ai_grid_policy_rollouts r
 CROSS JOIN platform.tenants t
 WHERE r.release_id = 'AGCF_PHASE_1_INITIAL'
   AND t.status = 'ACTIVE' AND t.deleted_at IS NULL
ON CONFLICT (rollout_id, tenant_id) DO NOTHING;
