package com.prototype.vulnwatch.domain;

public enum FindingCloseReason {
    MANUAL_FIXED,
    MANUAL_FALSE_POSITIVE,
    MANUAL_ACCEPTED_RISK,
    VERIFIED_REMEDIATION,
    AUTO_NOT_OBSERVED,
    AUTO_COMPONENT_REMOVED,
    AUTO_ASSET_RETIRED,
    AUTO_DUPLICATE,
    AUTO_SOURCE_DISABLED,
    AUTO_POLICY_NOT_OWNER_FACING,
    AUTO_POLICY_PLATFORM_DEPRECATED,
    AUTO_POLICY_TENANT_DISABLED,
    AUTO_POLICY_VERSION_SUPERSEDED,
    AUTO_SUPPRESSED_BY_RULE
}
