-- Postgres-safe core schema baseline for empty databases.
-- This migration is intentionally idempotent so it can also run on schemas that
-- already have the tables created by Hibernate or earlier incremental Flyway migrations.
-- Note: vulnerability_targets is defined manually here because it was still absent
-- from the working bootstrap schema when this baseline was generated.
-- Note: vulnerability_config_expr and vulnerability_intel_observations are excluded here
-- because they are already fully owned by V1007 and V1008.

CREATE TABLE IF NOT EXISTS public.applicability_assessments (
    id bigint NOT NULL,
    affected_components text,
    assessed_by character varying(100),
    attack_vector_accessible boolean,
    completed_at timestamp(6) with time zone,
    confidence_level character varying(20),
    configuration_details text,
    created_at timestamp(6) with time zone NOT NULL,
    current_version character varying(100),
    detection_method character varying(100),
    final_result character varying(50),
    fixed_version character varying(100),
    justification text,
    recommended_action text,
    software_detected boolean,
    status character varying(50) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    vulnerable_configuration boolean,
    vulnerable_version_present boolean,
    vulnerable_version_range character varying(200),
    tenant_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT applicability_assessments_confidence_level_check CHECK (((confidence_level)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT applicability_assessments_final_result_check CHECK (((final_result)::text = ANY ((ARRAY['AFFECTED'::character varying, 'NOT_AFFECTED'::character varying, 'UNDER_INVESTIGATION'::character varying, 'INCONCLUSIVE'::character varying])::text[]))),
    CONSTRAINT applicability_assessments_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'applicability_assessments'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE $ddl$
ALTER TABLE public.applicability_assessments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applicability_assessments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
$ddl$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.assets (
    id uuid NOT NULL,
    business_criticality character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    environment character varying(64),
    identifier character varying(255) NOT NULL,
    last_cmdb_sync_at timestamp(6) with time zone,
    last_inventory_at timestamp(6) with time zone,
    name character varying(255) NOT NULL,
    owner_email character varying(255),
    owner_team character varying(255),
    service_name character varying(255),
    state character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    tenant_id uuid NOT NULL,
    CONSTRAINT assets_business_criticality_check CHECK (((business_criticality)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT assets_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'RETIRED'::character varying, 'DECOMMISSIONED'::character varying])::text[]))),
    CONSTRAINT assets_type_check CHECK (((type)::text = ANY ((ARRAY['APPLICATION'::character varying, 'HOST'::character varying, 'CONTAINER_IMAGE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.component_vulnerability_states (
    id uuid NOT NULL,
    applicability_reason character varying(255),
    applicability_state character varying(40) NOT NULL,
    confidence_score double precision,
    created_at timestamp(6) with time zone NOT NULL,
    eligible_for_finding boolean NOT NULL,
    impact_reason character varying(255),
    impact_state character varying(40) NOT NULL,
    last_evaluated_at timestamp(6) with time zone NOT NULL,
    matched_by character varying(120),
    precedence_reason character varying(120),
    state_changed_at timestamp(6) with time zone NOT NULL,
    trace_json oid,
    updated_at timestamp(6) with time zone NOT NULL,
    vex_freshness character varying(40),
    vex_provider character varying(120),
    vex_source character varying(120),
    vex_status character varying(80),
    vex_target_id uuid,
    component_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT component_vulnerability_states_applicability_state_check CHECK (((applicability_state)::text = ANY ((ARRAY['APPLICABLE'::character varying, 'NOT_APPLICABLE'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT component_vulnerability_states_impact_state_check CHECK (((impact_state)::text = ANY ((ARRAY['IMPACTED'::character varying, 'NOT_IMPACTED'::character varying, 'FIXED'::character varying, 'NO_PATCH'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.cpe_dim (
    id uuid NOT NULL,
    cpe_key character varying(1000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    edition character varying(500),
    language character varying(500),
    normalized_cpe character varying(1200) NOT NULL,
    other character varying(500),
    part character varying(500) NOT NULL,
    product character varying(500) NOT NULL,
    raw_cpe character varying(1200) NOT NULL,
    sw_edition character varying(500),
    target_hw character varying(500),
    target_sw character varying(500),
    update character varying(500),
    updated_at timestamp(6) with time zone NOT NULL,
    vendor character varying(500) NOT NULL,
    version character varying(500)
);

CREATE TABLE IF NOT EXISTS public.finding_comments (
    id uuid NOT NULL,
    author character varying(255) NOT NULL,
    body character varying(4000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    finding_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.finding_events (
    id uuid NOT NULL,
    actor character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    details_json oid,
    event_type character varying(128) NOT NULL,
    summary character varying(1000) NOT NULL,
    finding_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.findings (
    id uuid NOT NULL,
    assigned_at timestamp(6) with time zone,
    assigned_by character varying(255),
    assigned_to character varying(255),
    confidence_score double precision,
    created_at timestamp(6) with time zone NOT NULL,
    decision_state character varying(40),
    due_at timestamp(6) with time zone,
    evidence oid,
    first_observed_at timestamp(6) with time zone,
    last_observed_at timestamp(6) with time zone,
    matched_by character varying(255) NOT NULL,
    precedence_trace oid,
    risk_score double precision NOT NULL,
    status character varying(255) NOT NULL,
    suppressed_until timestamp(6) with time zone,
    suppression_reason character varying(2000),
    updated_at timestamp(6) with time zone NOT NULL,
    vex_freshness character varying(64),
    vex_provider character varying(128),
    vex_status character varying(64),
    asset_id uuid NOT NULL,
    component_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT findings_decision_state_check CHECK (((decision_state)::text = ANY ((ARRAY['AFFECTED'::character varying, 'NOT_AFFECTED'::character varying, 'FIXED'::character varying, 'UNDER_INVESTIGATION'::character varying, 'NEEDS_REVIEW'::character varying])::text[]))),
    CONSTRAINT findings_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying, 'SUPPRESSED'::character varying, 'AUTO_CLOSED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.github_sbom_sources (
    id uuid NOT NULL,
    asset_identifier character varying(255) NOT NULL,
    asset_name character varying(255) NOT NULL,
    asset_type character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    enabled boolean NOT NULL,
    frequency character varying(255) NOT NULL,
    interval_minutes integer NOT NULL,
    last_error character varying(2000),
    last_run_at timestamp(6) with time zone,
    last_run_status character varying(64),
    name character varying(255) NOT NULL,
    owner character varying(255) NOT NULL,
    path character varying(1000) NOT NULL,
    repo character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT github_sbom_sources_asset_type_check CHECK (((asset_type)::text = ANY ((ARRAY['APPLICATION'::character varying, 'HOST'::character varying, 'CONTAINER_IMAGE'::character varying])::text[]))),
    CONSTRAINT github_sbom_sources_frequency_check CHECK (((frequency)::text = ANY ((ARRAY['ONCE'::character varying, 'INTERVAL'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.identity_links (
    id uuid NOT NULL,
    confidence double precision,
    created_at timestamp(6) with time zone NOT NULL,
    link_type character varying(80) NOT NULL,
    source character varying(80) NOT NULL,
    verified boolean NOT NULL,
    from_identifier_id uuid NOT NULL,
    to_identifier_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inventory_component_cpe_map (
    id uuid NOT NULL,
    first_seen_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    observed_version character varying(255),
    component_id uuid NOT NULL,
    cpe_id uuid NOT NULL,
    tenant_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.inventory_components (
    id uuid NOT NULL,
    component_digest character varying(120),
    component_status character varying(255) NOT NULL,
    coord_key character varying(500),
    ecosystem character varying(255) NOT NULL,
    ingested_at timestamp(6) with time zone NOT NULL,
    last_observed_at timestamp(6) with time zone NOT NULL,
    normalized_name character varying(500),
    normalized_purl character varying(1200),
    normalized_version character varying(255),
    package_name character varying(255) NOT NULL,
    purl character varying(255) NOT NULL,
    retired_at timestamp(6) with time zone,
    software_model_result character varying(500),
    version character varying(255) NOT NULL,
    asset_id uuid NOT NULL,
    sbom_upload_id uuid NOT NULL,
    software_identity_id uuid,
    tenant_id uuid NOT NULL,
    CONSTRAINT inventory_components_component_status_check CHECK (((component_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RETIRED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.investigation_activities (
    id bigint NOT NULL,
    activity_type character varying(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    metadata text,
    performed_by character varying(100),
    investigation_id bigint NOT NULL,
    CONSTRAINT investigation_activities_activity_type_check CHECK (((activity_type)::text = ANY ((ARRAY['CREATED'::character varying, 'STATUS_CHANGED'::character varying, 'ASSIGNED'::character varying, 'NOTES_UPDATED'::character varying, 'ATTACHMENT_ADDED'::character varying, 'COMMENT_ADDED'::character varying, 'PRIORITY_CHANGED'::character varying, 'CLOSED'::character varying, 'REOPENED'::character varying])::text[])))
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'investigation_activities'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE $ddl$
ALTER TABLE public.investigation_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investigation_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
$ddl$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.investigation_attachments (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_size bigint,
    file_type character varying(100),
    storage_path character varying(500) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    uploaded_by character varying(100),
    investigation_id bigint NOT NULL
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'investigation_attachments'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE $ddl$
ALTER TABLE public.investigation_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investigation_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
$ddl$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.investigations (
    id bigint NOT NULL,
    assigned_to character varying(100),
    business_impact text,
    closed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(100),
    exploit_available boolean,
    exploit_details text,
    mitigation_steps text,
    modified_by character varying(100),
    notes text,
    patch_available boolean,
    patch_details text,
    priority character varying(20),
    vuln_references text,
    status character varying(50) NOT NULL,
    systems_affected text,
    updated_at timestamp(6) with time zone NOT NULL,
    tenant_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT investigations_priority_check CHECK (((priority)::text = ANY ((ARRAY['CRITICAL'::character varying, 'HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT investigations_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'PENDING_REVIEW'::character varying, 'CLOSED'::character varying, 'REOPENED'::character varying])::text[])))
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'investigations'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    EXECUTE $ddl$
ALTER TABLE public.investigations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investigations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
$ddl$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.org_cve_records (
    id uuid NOT NULL,
    applicability_state character varying(40) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    cvss_score double precision,
    epss_score double precision,
    external_id character varying(255) NOT NULL,
    impact_reason character varying(120),
    impact_state character varying(40) NOT NULL,
    impacted boolean NOT NULL,
    in_kev boolean NOT NULL,
    last_evaluated_at timestamp(6) with time zone NOT NULL,
    matched_component_count bigint NOT NULL,
    matched_software_count bigint NOT NULL,
    severity character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    vuln_status character varying(255),
    tenant_id uuid NOT NULL,
    vulnerability_id uuid NOT NULL,
    CONSTRAINT org_cve_records_applicability_state_check CHECK (((applicability_state)::text = ANY ((ARRAY['APPLICABLE'::character varying, 'NOT_APPLICABLE'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT org_cve_records_impact_state_check CHECK (((impact_state)::text = ANY ((ARRAY['IMPACTED'::character varying, 'NOT_IMPACTED'::character varying, 'FIXED'::character varying, 'NO_PATCH'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.risk_policies (
    id uuid NOT NULL,
    asset_critical_risk_boost double precision NOT NULL,
    asset_critical_sla_multiplier double precision NOT NULL,
    asset_high_risk_boost double precision NOT NULL,
    asset_high_sla_multiplier double precision NOT NULL,
    asset_low_risk_boost double precision NOT NULL,
    asset_low_sla_multiplier double precision NOT NULL,
    asset_medium_risk_boost double precision NOT NULL,
    asset_medium_sla_multiplier double precision NOT NULL,
    auto_close_after_days integer NOT NULL,
    auto_close_asset_identifier character varying(255),
    auto_close_enabled boolean NOT NULL,
    critical_sla_days integer NOT NULL,
    critical_threshold double precision NOT NULL,
    cvss_weight double precision NOT NULL,
    epss_weight double precision NOT NULL,
    finding_generation_mode character varying(20) NOT NULL,
    high_sla_days integer NOT NULL,
    high_threshold double precision NOT NULL,
    kev_boost double precision NOT NULL,
    low_sla_days integer NOT NULL,
    medium_sla_days integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    vex_fixed_freshness_days integer NOT NULL,
    vex_known_affected_boost double precision NOT NULL,
    vex_not_affected_freshness_days integer NOT NULL,
    vex_not_affected_reduction double precision NOT NULL,
    vex_stale_penalty double precision NOT NULL,
    vex_under_investigation_penalty double precision NOT NULL,
    tenant_id uuid NOT NULL,
    CONSTRAINT risk_policies_finding_generation_mode_check CHECK (((finding_generation_mode)::text = ANY ((ARRAY['AUTO'::character varying, 'MANUAL'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.sbom_uploads (
    id uuid NOT NULL,
    component_count integer,
    content_length_bytes bigint,
    content_sha256 character varying(128),
    content_type character varying(512),
    evidence_json oid,
    fetch_status_code integer,
    findings_generated integer,
    format character varying(255) NOT NULL,
    ingestion_source_system character varying(64),
    ingestion_source_type character varying(64),
    original_filename character varying(10000) NOT NULL,
    source_endpoint character varying(10000),
    source_reference character varying(10000),
    status character varying(32) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    asset_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    CONSTRAINT sbom_uploads_format_check CHECK (((format)::text = ANY ((ARRAY['CYCLONEDX'::character varying, 'SPDX'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT sbom_uploads_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'SUCCESS'::character varying, 'FAILURE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.software_identifiers (
    id uuid NOT NULL,
    confidence double precision,
    created_at timestamp(6) with time zone NOT NULL,
    id_type character varying(40) NOT NULL,
    normalized_value character varying(1000) NOT NULL,
    raw_value character varying(1000),
    source character varying(80) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    verified boolean NOT NULL,
    software_identity_id uuid NOT NULL,
    CONSTRAINT software_identifiers_id_type_check CHECK (((id_type)::text = ANY ((ARRAY['PURL'::character varying, 'COORD'::character varying, 'CPE'::character varying, 'REPO_URL'::character varying, 'SWID'::character varying, 'MAVEN'::character varying, 'NPM'::character varying, 'PYPI'::character varying, 'GOLANG'::character varying, 'RPM'::character varying, 'DEB'::character varying, 'APK'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.software_identities (
    id uuid NOT NULL,
    canonical_key character varying(400) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(300) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.software_inventory_items (
    id uuid NOT NULL,
    component_status character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    ecosystem character varying(255) NOT NULL,
    first_seen_at timestamp(6) with time zone NOT NULL,
    last_observed_at timestamp(6) with time zone,
    package_name character varying(255) NOT NULL,
    purl character varying(255) NOT NULL,
    synced_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    version character varying(255) NOT NULL,
    asset_id uuid,
    component_id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    CONSTRAINT software_inventory_items_component_status_check CHECK (((component_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RETIRED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.sync_runs (
    id uuid NOT NULL,
    completed_at timestamp(6) with time zone,
    error_message character varying(2000),
    records_failed integer NOT NULL,
    records_fetched integer NOT NULL,
    records_inserted integer NOT NULL,
    records_updated integer NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    sync_type character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tenants (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vulnerabilities (
    id uuid NOT NULL,
    attack_complexity character varying(20),
    attack_vector character varying(20),
    created_at timestamp(6) with time zone NOT NULL,
    cvss_score double precision,
    cvss_vector character varying(300),
    cvss_version character varying(20),
    cwe_ids character varying(200),
    description_archive_key character varying(200),
    description_snippet character varying(500),
    epss_score double precision,
    exploitability_score double precision,
    external_id character varying(50) NOT NULL,
    impact_score double precision,
    in_kev boolean NOT NULL,
    last_modified_at timestamp(6) with time zone,
    privileges_required character varying(20),
    published_at timestamp(6) with time zone,
    raw_payload_archive_key character varying(200),
    references_json oid,
    cvss_scope character varying(20),
    severity character varying(20) NOT NULL,
    source character varying(20) NOT NULL,
    source_identifier character varying(255),
    title character varying(500) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_interaction character varying(20),
    vuln_status character varying(80),
    CONSTRAINT vulnerabilities_source_check CHECK (((source)::text = ANY ((ARRAY['NVD'::character varying, 'KEV'::character varying, 'ADVISORY'::character varying, 'CSAF'::character varying, 'VEX'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.vulnerability_intel_summary (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    cvss_score double precision,
    description_snippet character varying(220),
    epss_score double precision,
    external_id character varying(255) NOT NULL,
    in_kev boolean NOT NULL,
    last_modified_at timestamp(6) with time zone,
    published_at timestamp(6) with time zone,
    severity character varying(255) NOT NULL,
    source_count integer NOT NULL,
    summary_updated_at timestamp(6) with time zone NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    vuln_status character varying(255),
    vulnerability_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vulnerability_intel_summary_sources (
    id uuid NOT NULL,
    source_system character varying(80) NOT NULL,
    vulnerability_id uuid NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vulnerability_rules (
    id uuid NOT NULL,
    cpe character varying(255),
    cpe_product character varying(255),
    cpe_vendor character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    ecosystem character varying(255) NOT NULL,
    package_name character varying(255) NOT NULL,
    version_end character varying(255),
    version_end_inclusive boolean,
    version_exact character varying(255),
    version_start character varying(255),
    version_start_inclusive boolean,
    vulnerability_id uuid NOT NULL
);

DO $$
BEGIN
  IF to_regclass('public.applicability_assessments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'applicability_assessments_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.applicability_assessments
    ADD CONSTRAINT applicability_assessments_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.assets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'assets_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.component_vulnerability_states') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'component_vulnerability_states_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.component_vulnerability_states
    ADD CONSTRAINT component_vulnerability_states_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.cpe_dim') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'cpe_dim_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.cpe_dim
    ADD CONSTRAINT cpe_dim_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.finding_comments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'finding_comments_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.finding_comments
    ADD CONSTRAINT finding_comments_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.finding_events') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'finding_events_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.finding_events
    ADD CONSTRAINT finding_events_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'findings_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT findings_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.github_sbom_sources') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'github_sbom_sources_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.github_sbom_sources
    ADD CONSTRAINT github_sbom_sources_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.identity_links') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'identity_links_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.identity_links
    ADD CONSTRAINT identity_links_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_component_cpe_map') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'inventory_component_cpe_map_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_component_cpe_map
    ADD CONSTRAINT inventory_component_cpe_map_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_components') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'inventory_components_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_components
    ADD CONSTRAINT inventory_components_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigation_activities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'investigation_activities_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigation_activities
    ADD CONSTRAINT investigation_activities_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigation_attachments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'investigation_attachments_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigation_attachments
    ADD CONSTRAINT investigation_attachments_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigations') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'investigations_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigations
    ADD CONSTRAINT investigations_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.org_cve_records') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'org_cve_records_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.org_cve_records
    ADD CONSTRAINT org_cve_records_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.risk_policies') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'risk_policies_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.risk_policies
    ADD CONSTRAINT risk_policies_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.sbom_uploads') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'sbom_uploads_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.sbom_uploads
    ADD CONSTRAINT sbom_uploads_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_identifiers') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'software_identifiers_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_identifiers
    ADD CONSTRAINT software_identifiers_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_identities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'software_identities_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_identities
    ADD CONSTRAINT software_identities_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_inventory_items') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'software_inventory_items_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_inventory_items
    ADD CONSTRAINT software_inventory_items_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.sync_runs') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'sync_runs_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.sync_runs
    ADD CONSTRAINT sync_runs_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.tenants') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'tenants_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.risk_policies') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk1h6e8xh3dq7eddoh1930vmfje'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.risk_policies
    ADD CONSTRAINT uk1h6e8xh3dq7eddoh1930vmfje UNIQUE (tenant_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.tenants') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk4moql6miwoh3w0drxa2gmjbll'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk4moql6miwoh3w0drxa2gmjbll UNIQUE (name);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_intel_summary') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk8f0oogu8p1m7lpdj6y4cybvsx'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_intel_summary
    ADD CONSTRAINT uk8f0oogu8p1m7lpdj6y4cybvsx UNIQUE (vulnerability_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.assets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_assets_tenant_identifier'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.assets
    ADD CONSTRAINT uk_assets_tenant_identifier UNIQUE (tenant_id, identifier);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.component_vulnerability_states') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_component_vuln_state_tenant_component_vulnerability'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.component_vulnerability_states
    ADD CONSTRAINT uk_component_vuln_state_tenant_component_vulnerability UNIQUE (tenant_id, component_id, vulnerability_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.cpe_dim') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_cpe_dim_normalized'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.cpe_dim
    ADD CONSTRAINT uk_cpe_dim_normalized UNIQUE (normalized_cpe);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_findings_component_vulnerability'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT uk_findings_component_vulnerability UNIQUE (component_id, vulnerability_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.identity_links') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_identity_links_pair_type_source'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.identity_links
    ADD CONSTRAINT uk_identity_links_pair_type_source UNIQUE (from_identifier_id, to_identifier_id, link_type, source);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_component_cpe_map') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_inventory_component_cpe'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_component_cpe_map
    ADD CONSTRAINT uk_inventory_component_cpe UNIQUE (tenant_id, component_id, cpe_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.org_cve_records') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_org_cve_record_tenant_vulnerability'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.org_cve_records
    ADD CONSTRAINT uk_org_cve_record_tenant_vulnerability UNIQUE (tenant_id, vulnerability_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_identifiers') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_software_identifier_identity_type_value'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_identifiers
    ADD CONSTRAINT uk_software_identifier_identity_type_value UNIQUE (software_identity_id, id_type, normalized_value);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_inventory_items') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_software_inventory_tenant_component'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_inventory_items
    ADD CONSTRAINT uk_software_inventory_tenant_component UNIQUE (tenant_id, component_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_intel_summary_sources') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'uk_vintel_summary_source_vuln_source'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_intel_summary_sources
    ADD CONSTRAINT uk_vintel_summary_source_vuln_source UNIQUE (vulnerability_id, source_system);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerabilities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'ukk0u03yrh1kgd9yhqjj2xp0h42'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerabilities
    ADD CONSTRAINT ukk0u03yrh1kgd9yhqjj2xp0h42 UNIQUE (external_id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_identities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'ukovmqhj83h6l81mbsdauxb15c0'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_identities
    ADD CONSTRAINT ukovmqhj83h6l81mbsdauxb15c0 UNIQUE (canonical_key);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerabilities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'vulnerabilities_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerabilities
    ADD CONSTRAINT vulnerabilities_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_intel_summary') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'vulnerability_intel_summary_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_intel_summary
    ADD CONSTRAINT vulnerability_intel_summary_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_intel_summary_sources') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'vulnerability_intel_summary_sources_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_intel_summary_sources
    ADD CONSTRAINT vulnerability_intel_summary_sources_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_rules') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'vulnerability_rules_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_rules
    ADD CONSTRAINT vulnerability_rules_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_assets_tenant_id ON public.assets USING btree (tenant_id);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_applicability ON public.component_vulnerability_states USING btree (tenant_id, applicability_state);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_component_vuln ON public.component_vulnerability_states USING btree (tenant_id, component_id, vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_eligible ON public.component_vulnerability_states USING btree (tenant_id, eligible_for_finding);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_impact ON public.component_vulnerability_states USING btree (tenant_id, impact_state);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_impact_updated ON public.component_vulnerability_states USING btree (tenant_id, impact_state, updated_at);

CREATE INDEX IF NOT EXISTS idx_comp_vuln_state_tenant_vuln_impact ON public.component_vulnerability_states USING btree (tenant_id, vulnerability_id, impact_state);

CREATE INDEX IF NOT EXISTS idx_cpe_dim_key ON public.cpe_dim USING btree (cpe_key);

CREATE INDEX IF NOT EXISTS idx_cpe_dim_normalized ON public.cpe_dim USING btree (normalized_cpe);

CREATE INDEX IF NOT EXISTS idx_finding_comments_finding_created ON public.finding_comments USING btree (finding_id, created_at);

CREATE INDEX IF NOT EXISTS idx_finding_events_finding_created ON public.finding_events USING btree (finding_id, created_at);

CREATE INDEX IF NOT EXISTS idx_findings_asset_id ON public.findings USING btree (asset_id);

CREATE INDEX IF NOT EXISTS idx_findings_tenant_component_vuln ON public.findings USING btree (tenant_id, component_id, vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_findings_tenant_status_updated ON public.findings USING btree (tenant_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_findings_vex_freshness ON public.findings USING btree (vex_freshness);

CREATE INDEX IF NOT EXISTS idx_findings_vex_provider ON public.findings USING btree (vex_provider);

CREATE INDEX IF NOT EXISTS idx_findings_vex_status ON public.findings USING btree (vex_status);

CREATE INDEX IF NOT EXISTS idx_findings_vulnerability_id ON public.findings USING btree (vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_findings_vulnerability_status ON public.findings USING btree (vulnerability_id, status);

CREATE INDEX IF NOT EXISTS idx_github_sbom_sources_enabled ON public.github_sbom_sources USING btree (enabled, last_run_at);

CREATE INDEX IF NOT EXISTS idx_iccm_tenant_component ON public.inventory_component_cpe_map USING btree (tenant_id, component_id);

CREATE INDEX IF NOT EXISTS idx_iccm_tenant_cpe ON public.inventory_component_cpe_map USING btree (tenant_id, cpe_id);

CREATE INDEX IF NOT EXISTS idx_identity_links_from ON public.identity_links USING btree (from_identifier_id);

CREATE INDEX IF NOT EXISTS idx_identity_links_to ON public.identity_links USING btree (to_identifier_id);

CREATE INDEX IF NOT EXISTS idx_inventory_component_digest ON public.inventory_components USING btree (component_digest);

CREATE INDEX IF NOT EXISTS idx_inventory_coord_key_tenant ON public.inventory_components USING btree (coord_key, tenant_id);

CREATE INDEX IF NOT EXISTS idx_inventory_norm_purl_tenant ON public.inventory_components USING btree (normalized_purl, tenant_id);

CREATE INDEX IF NOT EXISTS idx_inventory_sbom_upload ON public.inventory_components USING btree (sbom_upload_id);

CREATE INDEX IF NOT EXISTS idx_inventory_software_identity ON public.inventory_components USING btree (software_identity_id);

CREATE INDEX IF NOT EXISTS idx_inventory_tenant_asset ON public.inventory_components USING btree (tenant_id, asset_id);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_applicability ON public.org_cve_records USING btree (tenant_id, applicability_state);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_external_id ON public.org_cve_records USING btree (tenant_id, external_id);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_impact_state ON public.org_cve_records USING btree (tenant_id, impact_state);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_impacted ON public.org_cve_records USING btree (tenant_id, impacted);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_rank ON public.org_cve_records USING btree (tenant_id, impacted, applicability_state, cvss_score, external_id);

CREATE INDEX IF NOT EXISTS idx_org_cve_record_tenant_vulnerability ON public.org_cve_records USING btree (tenant_id, vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_sbom_upload_asset_uploaded ON public.sbom_uploads USING btree (asset_id, uploaded_at);

CREATE INDEX IF NOT EXISTS idx_sbom_upload_tenant_uploaded ON public.sbom_uploads USING btree (tenant_id, uploaded_at);

CREATE INDEX IF NOT EXISTS idx_software_identifier_identity ON public.software_identifiers USING btree (software_identity_id);

CREATE INDEX IF NOT EXISTS idx_software_identifier_type_value ON public.software_identifiers USING btree (id_type, normalized_value);

CREATE INDEX IF NOT EXISTS idx_software_identity_key ON public.software_identities USING btree (canonical_key);

CREATE INDEX IF NOT EXISTS idx_software_inventory_tenant_component ON public.software_inventory_items USING btree (tenant_id, component_id);

CREATE INDEX IF NOT EXISTS idx_software_inventory_tenant_pkg ON public.software_inventory_items USING btree (tenant_id, ecosystem, package_name, version);

CREATE INDEX IF NOT EXISTS idx_software_inventory_tenant_status ON public.software_inventory_items USING btree (tenant_id, component_status);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_cvss_lastmod_updated ON public.vulnerability_intel_summary USING btree (cvss_score, last_modified_at, updated_at);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_external_cvss_lastmod_updated ON public.vulnerability_intel_summary USING btree (external_id, cvss_score, last_modified_at, updated_at);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_external_id ON public.vulnerability_intel_summary USING btree (external_id);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_in_kev ON public.vulnerability_intel_summary USING btree (in_kev);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_severity ON public.vulnerability_intel_summary USING btree (severity);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_source_source ON public.vulnerability_intel_summary_sources USING btree (source_system);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_source_vuln ON public.vulnerability_intel_summary_sources USING btree (vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_source_vuln_source ON public.vulnerability_intel_summary_sources USING btree (vulnerability_id, source_system);

CREATE INDEX IF NOT EXISTS idx_vintel_summary_vuln_status ON public.vulnerability_intel_summary USING btree (vuln_status);

CREATE INDEX IF NOT EXISTS idx_vuln_rules_ecosystem_package ON public.vulnerability_rules USING btree (ecosystem, package_name);

CREATE INDEX IF NOT EXISTS idx_vuln_rules_vulnerability ON public.vulnerability_rules USING btree (vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_cvss_lastmod_updated ON public.vulnerabilities USING btree (cvss_score, last_modified_at, updated_at);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_epss ON public.vulnerabilities USING btree (epss_score);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_external_cvss_lastmod_updated ON public.vulnerabilities USING btree (external_id, cvss_score, last_modified_at, updated_at);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_in_kev ON public.vulnerabilities USING btree (in_kev);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_published ON public.vulnerabilities USING btree (published_at);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_severity ON public.vulnerabilities USING btree (severity);

DO $$
BEGIN
  IF to_regclass('public.applicability_assessments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk16k9id2eb74jekwmies27lgno'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.applicability_assessments
    ADD CONSTRAINT fk16k9id2eb74jekwmies27lgno FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.identity_links') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk17ccjx3613opckf1at9rqcm9o'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.identity_links
    ADD CONSTRAINT fk17ccjx3613opckf1at9rqcm9o FOREIGN KEY (to_identifier_id) REFERENCES public.software_identifiers(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_rules') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk1c5t5m58f1ji584r7dux32eo6'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_rules
    ADD CONSTRAINT fk1c5t5m58f1ji584r7dux32eo6 FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk1uiun2qsulcvmhpc6fcvxtxgb'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT fk1uiun2qsulcvmhpc6fcvxtxgb FOREIGN KEY (asset_id) REFERENCES public.assets(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigations') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk3wgcprkxy8dt0jqe2gy2m13mb'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigations
    ADD CONSTRAINT fk3wgcprkxy8dt0jqe2gy2m13mb FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.org_cve_records') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk5paxfny763ohvot5dvl75wf3l'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.org_cve_records
    ADD CONSTRAINT fk5paxfny763ohvot5dvl75wf3l FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.component_vulnerability_states') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk6vnf7qqmirn15bvbnh82okxlc'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.component_vulnerability_states
    ADD CONSTRAINT fk6vnf7qqmirn15bvbnh82okxlc FOREIGN KEY (component_id) REFERENCES public.inventory_components(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_components') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk6wwlyy182rfl3jijmpq3qtq8k'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_components
    ADD CONSTRAINT fk6wwlyy182rfl3jijmpq3qtq8k FOREIGN KEY (asset_id) REFERENCES public.assets(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.component_vulnerability_states') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk7fdcbuot7n0l4t1h4j89j5lck'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.component_vulnerability_states
    ADD CONSTRAINT fk7fdcbuot7n0l4t1h4j89j5lck FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_components') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk7xxoo0j0g75i7xmwhgvntfpys'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_components
    ADD CONSTRAINT fk7xxoo0j0g75i7xmwhgvntfpys FOREIGN KEY (sbom_upload_id) REFERENCES public.sbom_uploads(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_components') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk93i44psr4hgyeogubirc1ipox'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_components
    ADD CONSTRAINT fk93i44psr4hgyeogubirc1ipox FOREIGN KEY (software_identity_id) REFERENCES public.software_identities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigation_activities') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fk9aokjo4k5to8idb6yuslq7ksn'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigation_activities
    ADD CONSTRAINT fk9aokjo4k5to8idb6yuslq7ksn FOREIGN KEY (investigation_id) REFERENCES public.investigations(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkaqg8gm1rhqb40ewm4n9mq5gbl'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT fkaqg8gm1rhqb40ewm4n9mq5gbl FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_component_cpe_map') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkbn79nrm3svp7wavib4erna8hd'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_component_cpe_map
    ADD CONSTRAINT fkbn79nrm3svp7wavib4erna8hd FOREIGN KEY (component_id) REFERENCES public.inventory_components(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkc2yh5bohc4mb5qihewlhcqglr'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT fkc2yh5bohc4mb5qihewlhcqglr FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.identity_links') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkdo9lqi6jgfao8rsgs8h9qng4g'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.identity_links
    ADD CONSTRAINT fkdo9lqi6jgfao8rsgs8h9qng4g FOREIGN KEY (from_identifier_id) REFERENCES public.software_identifiers(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.applicability_assessments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkdsmy3fn6j0g15bdfx83l3eakf'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.applicability_assessments
    ADD CONSTRAINT fkdsmy3fn6j0g15bdfx83l3eakf FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.sbom_uploads') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkfl1rgtitudexg8bwkhoh2owyg'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.sbom_uploads
    ADD CONSTRAINT fkfl1rgtitudexg8bwkhoh2owyg FOREIGN KEY (asset_id) REFERENCES public.assets(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.sbom_uploads') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkgvmw0ol9foc055d3s8wha7w5l'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.sbom_uploads
    ADD CONSTRAINT fkgvmw0ol9foc055d3s8wha7w5l FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.finding_events') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkh6gxoewc34uam30fktgi7oi9o'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.finding_events
    ADD CONSTRAINT fkh6gxoewc34uam30fktgi7oi9o FOREIGN KEY (finding_id) REFERENCES public.findings(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigations') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fki5ahe57q5d2ssxujg9tbaxsg6'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigations
    ADD CONSTRAINT fki5ahe57q5d2ssxujg9tbaxsg6 FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_identifiers') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkifk83byst6tuex9rpbhd9ji4n'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_identifiers
    ADD CONSTRAINT fkifk83byst6tuex9rpbhd9ji4n FOREIGN KEY (software_identity_id) REFERENCES public.software_identities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_inventory_items') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkj81rdb1o3u8l9jq3fwynfc65n'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_inventory_items
    ADD CONSTRAINT fkj81rdb1o3u8l9jq3fwynfc65n FOREIGN KEY (asset_id) REFERENCES public.assets(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_inventory_items') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkkv1pyouruhsokyys6wqe272r8'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_inventory_items
    ADD CONSTRAINT fkkv1pyouruhsokyys6wqe272r8 FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.software_inventory_items') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkl3brn6r8a5snh42ncu9woofaf'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.software_inventory_items
    ADD CONSTRAINT fkl3brn6r8a5snh42ncu9woofaf FOREIGN KEY (component_id) REFERENCES public.inventory_components(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_components') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkl4b2hq3rtjx9mg8ygo00t37ce'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_components
    ADD CONSTRAINT fkl4b2hq3rtjx9mg8ygo00t37ce FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_component_cpe_map') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkmgi0xlrjk5scq0varyoynmpko'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_component_cpe_map
    ADD CONSTRAINT fkmgi0xlrjk5scq0varyoynmpko FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.assets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkmi4k7902yp8htv1v4xd2fk705'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fkmi4k7902yp8htv1v4xd2fk705 FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.findings') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkmm0cv2wyk8thpybryslhknilf'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.findings
    ADD CONSTRAINT fkmm0cv2wyk8thpybryslhknilf FOREIGN KEY (component_id) REFERENCES public.inventory_components(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.component_vulnerability_states') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkohy971e3ksup96rdjw0en4rck'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.component_vulnerability_states
    ADD CONSTRAINT fkohy971e3ksup96rdjw0en4rck FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.inventory_component_cpe_map') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkom9ro57kn1wi6240uhxi0eba4'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.inventory_component_cpe_map
    ADD CONSTRAINT fkom9ro57kn1wi6240uhxi0eba4 FOREIGN KEY (cpe_id) REFERENCES public.cpe_dim(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.risk_policies') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkp0eh75c2j3jrd73rvh3jbwdxm'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.risk_policies
    ADD CONSTRAINT fkp0eh75c2j3jrd73rvh3jbwdxm FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.investigation_attachments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fkq4dht5hna43kqf286q7ur8d51'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.investigation_attachments
    ADD CONSTRAINT fkq4dht5hna43kqf286q7ur8d51 FOREIGN KEY (investigation_id) REFERENCES public.investigations(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.org_cve_records') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fks2y2d7vo43vktdb68q22yspwl'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.org_cve_records
    ADD CONSTRAINT fks2y2d7vo43vktdb68q22yspwl FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.finding_comments') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM pg_constraint
       WHERE conname = 'fktqnd5dl1fnom0jwb84agi5qka'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.finding_comments
    ADD CONSTRAINT fktqnd5dl1fnom0jwb84agi5qka FOREIGN KEY (finding_id) REFERENCES public.findings(id);
$ddl$;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.vulnerability_targets (
    id uuid NOT NULL,
    raw_target character varying(1200),
    normalized_target_key character varying(500) NOT NULL,
    ecosystem character varying(120),
    namespace character varying(120),
    package_name character varying(220),
    repo_url character varying(1200),
    version_exact character varying(255),
    version_start character varying(255),
    start_inclusive boolean,
    version_end character varying(255),
    end_inclusive boolean,
    introduced character varying(255),
    fixed character varying(255),
    version_scheme character varying(40) NOT NULL,
    constraint_type character varying(40),
    cpe character varying(1200),
    cpe_wildcard_score integer,
    qualifier_part character varying(40),
    qualifier_vendor character varying(255),
    qualifier_product character varying(255),
    qualifier_version character varying(255),
    qualifier_update character varying(255),
    qualifier_edition character varying(255),
    qualifier_language character varying(255),
    qualifier_sw_edition character varying(255),
    qualifier_target_sw character varying(255),
    qualifier_target_hw character varying(255),
    qualifier_other character varying(255),
    qualifiers_json text,
    source character varying(80) NOT NULL,
    kb_version character varying(120),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    cpe_id uuid,
    software_identity_id uuid,
    vulnerability_id uuid NOT NULL,
    target_type character varying(40) NOT NULL,
    CONSTRAINT vulnerability_targets_constraint_type_check CHECK (((constraint_type)::text = ANY ((ARRAY['NONE'::character varying, 'EXACT'::character varying, 'RANGE'::character varying, 'INTRODUCED_FIXED'::character varying])::text[]))),
    CONSTRAINT vulnerability_targets_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['PURL'::character varying, 'COORD'::character varying, 'ADVISORY_PACKAGE'::character varying, 'REPO'::character varying, 'CPE'::character varying, 'DIGEST'::character varying])::text[]))),
    CONSTRAINT vulnerability_targets_version_scheme_check CHECK (((version_scheme)::text = ANY ((ARRAY['SEMVER'::character varying, 'MAVEN'::character varying, 'PEP440'::character varying, 'DPKG'::character varying, 'RPM'::character varying, 'LEXICAL'::character varying, 'UNKNOWN'::character varying])::text[])))
);

DO $$
BEGIN
  IF to_regclass('public.vulnerability_targets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'vulnerability_targets_pkey'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_targets
    ADD CONSTRAINT vulnerability_targets_pkey PRIMARY KEY (id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_targets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'fk_vuln_targets_vulnerability'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_targets
    ADD CONSTRAINT fk_vuln_targets_vulnerability FOREIGN KEY (vulnerability_id) REFERENCES public.vulnerabilities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_targets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'fk_vuln_targets_software_identity'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_targets
    ADD CONSTRAINT fk_vuln_targets_software_identity FOREIGN KEY (software_identity_id) REFERENCES public.software_identities(id);
$ddl$;
  END IF;
END $$;

DO $$
BEGIN
  IF to_regclass('public.vulnerability_targets') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM pg_constraint WHERE conname = 'fk_vuln_targets_cpe'
     ) THEN
    EXECUTE $ddl$
ALTER TABLE ONLY public.vulnerability_targets
    ADD CONSTRAINT fk_vuln_targets_cpe FOREIGN KEY (cpe_id) REFERENCES public.cpe_dim(id);
$ddl$;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_vuln_target_vuln ON public.vulnerability_targets USING btree (vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_vuln_target_type_key ON public.vulnerability_targets USING btree (target_type, normalized_target_key);

CREATE INDEX IF NOT EXISTS idx_vuln_target_package ON public.vulnerability_targets USING btree (package_name);

CREATE INDEX IF NOT EXISTS idx_vuln_target_identity ON public.vulnerability_targets USING btree (software_identity_id);

CREATE INDEX IF NOT EXISTS idx_vuln_target_cpe_id ON public.vulnerability_targets USING btree (cpe_id);

CREATE INDEX IF NOT EXISTS idx_vuln_target_type_cpe_id ON public.vulnerability_targets USING btree (target_type, cpe_id);
